# server:
#   port: 8082

spring:
  application:
    name: DEMO-APP
    
  boot:
    admin:  
      client:
        url: http://localhost:1111

management:
  endpoints:
    web:
      exposure:
        include: "*"
message: "This is a test message from config server!"
